// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ075wPaDlkob8EB9mkUckx6dc1d3HNtA',
    appId: '1:989401932983:web:d90f70c68487adfe465932',
    messagingSenderId: '989401932983',
    projectId: 'blogapp-697f7',
    authDomain: 'blogapp-697f7.firebaseapp.com',
    storageBucket: 'blogapp-697f7.appspot.com',
    measurementId: 'G-427GXXMJTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCPcG-s_rFzFHRWfSUWNHjX-TPqmk67mk',
    appId: '1:989401932983:android:fb5ec5e4885db2e1465932',
    messagingSenderId: '989401932983',
    projectId: 'blogapp-697f7',
    storageBucket: 'blogapp-697f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqXz6KQcRUyw_Ft0OBoFaiJToQV6aLlE8',
    appId: '1:989401932983:ios:ffd524106b2a72ba465932',
    messagingSenderId: '989401932983',
    projectId: 'blogapp-697f7',
    storageBucket: 'blogapp-697f7.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqXz6KQcRUyw_Ft0OBoFaiJToQV6aLlE8',
    appId: '1:989401932983:ios:ffd524106b2a72ba465932',
    messagingSenderId: '989401932983',
    projectId: 'blogapp-697f7',
    storageBucket: 'blogapp-697f7.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ075wPaDlkob8EB9mkUckx6dc1d3HNtA',
    appId: '1:989401932983:web:602dfcbcf612f291465932',
    messagingSenderId: '989401932983',
    projectId: 'blogapp-697f7',
    authDomain: 'blogapp-697f7.firebaseapp.com',
    storageBucket: 'blogapp-697f7.appspot.com',
    measurementId: 'G-50KMGWG44K',
  );
}
